services:
  - name: fastapi-tts
    type: web
    runtime: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: COQUI_TOS_AGREED
        value: "1"
    plan: free
